## Preparando a Conexão com o MongoDB

In [1]:
# Instanciar o MongoDB
# Windows Iniciar - RUN - cmd
# mongod
# abre o MongoDB
# New connection - Fill in connection fields individually 
# localhost - 27017 - CONNECT
# Ctrl-C para encerrar

In [1]:
import pandas as pd
#import json
#from datetime import datetime
from pymongo import MongoClient

String conexão local

mongodb://localhost:27017/?readPreference=primary&ssl=false&directConnection=true

String conexão remota

mongodb://capacidadedb:prodemge@10.100.21.110:27017/capacidadedb

In [3]:
# Estabelecemos a conexão ao Banco de Dados
conn = MongoClient('localhost', 27017)
db = conn.capacidadedb
db_pipa = db.pipaColBrokerDia

In [4]:
#convert entire collection to Pandas dataframe
df_pipa = pd.DataFrame(list(db_pipa.find()))
df_pipa

,_id,BROKER,DATA,PROGRAMA,QUANTIDADE,SERVICE_CLASS,SERVICE_NAME
0,61a45a9ee00aa4111044b0df,ETB160,2021-11-27T00:00:00.000Z,NSDGX047,6,SDGX,DETRAN
1,61a45a9fe00aa4111044b0e0,ETB160,2021-11-27T00:00:00.000Z,NSDAKG12,1,SDGX,DETRAN
2,61a45a9fe00aa4111044b0e1,ETB160,2021-11-27T00:00:00.000Z,NSDAKQ08,1,SDGX,DETRAN
3,61a45a9fe00aa4111044b0e2,ETB160,2021-11-27T00:00:00.000Z,NSDAKQ07,1,SDGX,DETRAN
4,61a45a9fe00aa4111044b0e3,ETB160,2021-11-27T00:00:00.000Z,NSDGX414,1,SDGX,DETRAN
...,...,...,...,...,...,...,...
71289,63575fb94fd74c598401f372,ETB170,2022-10-24T00:00:00.000Z,NSDGX500,217,SDGX,PORTALDETRAN
71290,63575fb94fd74c598401f373,ETB170,2022-10-24T00:00:00.000Z,NSDGX495,9,SDGX,PORTALDETRAN
71291,63575fb94fd74c598401f374,ETB170,2022-10-24T00:00:00.000Z,NSDGX469,121,SDGX,PORTALDETRAN
71292,63575fb94fd74c598401f375,ETB170,2022-10-24T00:00:00.000Z,NSDGX467,12,SDGX,PORTALDETRAN
71293,63575fb94fd74c598401f376,ETB170,2022-10-24T00:00:00.000Z,NSDGX466,6,SDGX,PORTALDETRAN

In [5]:
df_pipa1 = pd.DataFrame(list(db_pipa.find( {'PROGRAMA' : { '$eq' : "NSDGX500" }} )))
df_pipa1

,_id,BROKER,DATA,PROGRAMA,QUANTIDADE,SERVICE_CLASS,SERVICE_NAME
0,61a45a9fe00aa4111044b15e,ETB170,2021-11-27T00:00:00.000Z,NSDGX500,96,SDGX,PORTALDETRAN
1,61a45ab0e00aa4111044b206,ETB170,2021-11-26T00:00:00.000Z,NSDGX500,82,SDGX,PORTALDETRAN
2,61a45ac4e00aa4111044b2a5,ETB170,2021-11-25T00:00:00.000Z,NSDGX500,50,SDGX,PORTALDETRAN
3,61a45ad9e00aa4111044b341,ETB170,2021-11-24T00:00:00.000Z,NSDGX500,50,SDGX,PORTALDETRAN
4,61a45aeee00aa4111044b3de,ETB170,2021-11-23T00:00:00.000Z,NSDGX500,100,SDGX,PORTALDETRAN
...,...,...,...,...,...,...,...
577,63536b374fd74c2cf0e71b7e,ETB170,2022-10-21T00:00:00.000Z,NSDGX500,78,SDGX,PORTALDETRAN
578,6354bcb44fd74c99bb6305bf,ETB170,2022-10-22T00:00:00.000Z,NSDGX500,65,SDGX,PORTALDETRAN
579,63560dfa4fd74ceb7a5c19d8,ETB170,2022-10-24T00:00:00.000Z,NSDGX500,79,SDGX,PORTALDETRAN
580,63575f794fd74c598401f2c1,ETB170,2022-10-25T00:00:00.000Z,NSDGX500,176,SDGX,PORTALDETRAN
581,63575fb94fd74c598401f372,ETB170,2022-10-24T00:00:00.000Z,NSDGX500,217,SDGX,PORTALDETRAN

In [2]:
# Estabelecemos a conexão ao Banco de Dados
conn = MongoClient('localhost', 27017)

In [3]:
type(conn)

pymongo.mongo_client.MongoClient

In [4]:
# Listando os bancos de dados disponíveis
conn.list_database_names()

['admin', 'capacidadedb', 'config', 'local', 'tweetterdb']

In [5]:
# Definindo o objeto db
db = conn.capacidadedb

In [6]:
# Listando as coleções disponíveis
db.list_collection_names()

['pipaColBroker', 'teste2', 'filesystem']

In [8]:
db_pipa = db.pipaColBroker

## Consultando os Dados no MongoDB

In [7]:
# Retornando o documento criado
db.pipaColBroker.find_one()

{'_id': '61a45a9ee00aa4111044b0df',
 'BROKER': 'ETB160',
 'DATA': '2021-11-27T00:00:00.000Z',
 'PROGRAMA': 'NSDGX047',
 'QUANTIDADE': '6',
 'SERVICE_CLASS': 'SDGX',
 'SERVICE_NAME': 'DETRAN'}

In [9]:
#convert entire collection to Pandas dataframe
df_pipa = pd.DataFrame(list(db_pipa.find()))
df_pipa

,_id,BROKER,DATA,PROGRAMA,QUANTIDADE,SERVICE_CLASS,SERVICE_NAME
0,61a45a9ee00aa4111044b0df,ETB160,2021-11-27T00:00:00.000Z,NSDGX047,6,SDGX,DETRAN
1,61a45a9fe00aa4111044b0e0,ETB160,2021-11-27T00:00:00.000Z,NSDAKG12,1,SDGX,DETRAN
2,61a45a9fe00aa4111044b0e1,ETB160,2021-11-27T00:00:00.000Z,NSDAKQ08,1,SDGX,DETRAN
3,61a45a9fe00aa4111044b0e2,ETB160,2021-11-27T00:00:00.000Z,NSDAKQ07,1,SDGX,DETRAN
4,61a45a9fe00aa4111044b0e3,ETB160,2021-11-27T00:00:00.000Z,NSDGX414,1,SDGX,DETRAN
...,...,...,...,...,...,...,...
71289,63575fb94fd74c598401f372,ETB170,2022-10-24T00:00:00.000Z,NSDGX500,217,SDGX,PORTALDETRAN
71290,63575fb94fd74c598401f373,ETB170,2022-10-24T00:00:00.000Z,NSDGX495,9,SDGX,PORTALDETRAN
71291,63575fb94fd74c598401f374,ETB170,2022-10-24T00:00:00.000Z,NSDGX469,121,SDGX,PORTALDETRAN
71292,63575fb94fd74c598401f375,ETB170,2022-10-24T00:00:00.000Z,NSDGX467,12,SDGX,PORTALDETRAN
71293,63575fb94fd74c598401f376,ETB170,2022-10-24T00:00:00.000Z,NSDGX466,6,SDGX,PORTALDETRAN

In [9]:
#convert entire collection to Pandas dataframe

'''
test.find({"$or":[{'seller_email': 'test2@gmail.com'}, {'seller_email':'test1@gmail.com'}]})

test.find( 
    {
        'PROGRAMA': {
            '$eq': 'NSDGX500'
        }
    }
)

'''

df_pipa = pd.DataFrame(list(db_pipa.find( {'PROGRAMA' : { '$eq' : "NSDGX500" }} )))
df_pipa

,_id,BROKER,DATA,PROGRAMA,QUANTIDADE,SERVICE_CLASS,SERVICE_NAME
0,61a45a9fe00aa4111044b15e,ETB170,2021-11-27T00:00:00.000Z,NSDGX500,96,SDGX,PORTALDETRAN
1,61a45ab0e00aa4111044b206,ETB170,2021-11-26T00:00:00.000Z,NSDGX500,82,SDGX,PORTALDETRAN
2,61a45ac4e00aa4111044b2a5,ETB170,2021-11-25T00:00:00.000Z,NSDGX500,50,SDGX,PORTALDETRAN
3,61a45ad9e00aa4111044b341,ETB170,2021-11-24T00:00:00.000Z,NSDGX500,50,SDGX,PORTALDETRAN
4,61a45aeee00aa4111044b3de,ETB170,2021-11-23T00:00:00.000Z,NSDGX500,100,SDGX,PORTALDETRAN
...,...,...,...,...,...,...,...
577,63536b374fd74c2cf0e71b7e,ETB170,2022-10-21T00:00:00.000Z,NSDGX500,78,SDGX,PORTALDETRAN
578,6354bcb44fd74c99bb6305bf,ETB170,2022-10-22T00:00:00.000Z,NSDGX500,65,SDGX,PORTALDETRAN
579,63560dfa4fd74ceb7a5c19d8,ETB170,2022-10-24T00:00:00.000Z,NSDGX500,79,SDGX,PORTALDETRAN
580,63575f794fd74c598401f2c1,ETB170,2022-10-25T00:00:00.000Z,NSDGX500,176,SDGX,PORTALDETRAN
581,63575fb94fd74c598401f372,ETB170,2022-10-24T00:00:00.000Z,NSDGX500,217,SDGX,PORTALDETRAN

In [ ]:
# https://medium.com/analytics-vidhya/how-to-upload-a-pandas-dataframe-to-mongodb-ffa18c0953c1

# Upload a Pandas DataFrame to MongoDB

'''

# Imports
import pandas as pd
from pymongo import MongoClient
# Load csv dataset
data = pd.read_csv('<<INSERT NAME OF DATASET>>.csv')
# Connect to MongoDB
client =  MongoClient("mongodb+srv://<<YOUR USERNAME>>:<<PASSWORD>>@clustertest-icsum.mongodb.net/test?retryWrites=true&w=majority")
db = client['<<INSERT NAME OF DATABASE>>']
collection = db['<<INSERT NAME OF COLLECTION>>']
data.reset_index(inplace=True)
data_dict = data.to_dict("records")
# Insert collection
collection.insert_many(data_dict)


'''